/**
 * DAO for the `ai_summaries` table.
 *
 * Holds the conservative caregiver-facing rollups generated by Phase 4B.
 * Every summary row carries:
 *   - `evidence` — the structured set of observation / baseline ids the
 *     model cited (never raw HealthKit / FHIR payloads),
 *   - `recommended_actions` — a small, vetted set of next-step suggestions,
 *   - `prompt_version` + `model` so a regression in copy can be audited
 *     by the prompt that produced it.
 *
 * Phase 4 only reads from this table; the generation pipeline lands in
 * Phase 4B with its own write path.
 */

const CREATE_TABLE_SQL = `
  CREATE TABLE IF NOT EXISTS ai_summaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    care_recipient_id UUID NOT NULL REFERENCES care_recipients(id) ON DELETE CASCADE,
    summary_type TEXT NOT NULL,
    summary_text TEXT NOT NULL,
    evidence JSONB,
    recommended_actions JSONB,
    model TEXT,
    prompt_version TEXT,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    source_window_start TIMESTAMPTZ,
    source_window_end TIMESTAMPTZ,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );
`

const CREATE_INDEX_RECIPIENT_TYPE_GENERATED_SQL = `
  CREATE INDEX IF NOT EXISTS ai_summaries_recipient_type_generated_idx
    ON ai_summaries (care_recipient_id, summary_type, generated_at DESC);
`

const SELECT_BASE_PROJECTION = `
  SELECT id, care_recipient_id, summary_type, summary_text,
         evidence, recommended_actions, model, prompt_version,
         generated_at, source_window_start, source_window_end,
         metadata, created_at
    FROM ai_summaries
`

const SELECT_BY_RECIPIENT_SQL = `
  ${SELECT_BASE_PROJECTION}
   WHERE care_recipient_id = $1
   ORDER BY generated_at DESC
   LIMIT $2;
`

const SELECT_BY_RECIPIENT_TYPE_SQL = `
  ${SELECT_BASE_PROJECTION}
   WHERE care_recipient_id = $1 AND summary_type = $2
   ORDER BY generated_at DESC
   LIMIT $3;
`

/**
 * List AI summaries for a single care recipient, newest-first.
 *
 * Returns an empty array when no summaries exist — the dashboard renders
 * an honest "no summary yet" empty state rather than fabricating PHI.
 */
export async function fetchSummariesForRecipient(
  pool,
  recipientId,
  { summaryType = null, limit },
) {
  if (summaryType) {
    const { rows } = await pool.query(SELECT_BY_RECIPIENT_TYPE_SQL, [
      recipientId,
      summaryType,
      limit,
    ])
    return rows
  }
  const { rows } = await pool.query(SELECT_BY_RECIPIENT_SQL, [recipientId, limit])
  return rows
}

/**
 * Idempotent migration for `ai_summaries`. Must run after
 * `ensureCareRecipientSchema` because of the FK.
 */
export async function ensureAiSummarySchema(pool) {
  await pool.query(CREATE_TABLE_SQL)
  await pool.query(CREATE_INDEX_RECIPIENT_TYPE_GENERATED_SQL)
}
